
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dh_database
    username: root
    password: 0721~Forever
  profiles:
    active: dev

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      password: 0721~Forever
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    bucketName: image-container

recaptcha:
  server-key: "6LdzFgAqAAAAAPuT4BLfBtNn_yGbjbOEIliaLyP8"
  siteVerify: "https://www.recaptcha.net/recaptcha/api/siteverify"

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: port
server:
  port: 8083
